version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: stefano-app
    restart: always
    environment:
      NODE_ENV: production
      PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    networks:
      - stefano-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: stefano-db
    restart: always
    environment:
      POSTGRES_DB: stefano
      POSTGRES_USER: stefano
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stefano-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stefano -d stefano"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: stefano-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.simple.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - stefano-network
    depends_on:
      app:
        condition: service_healthy

networks:
  stefano-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local